[config]
target = P4G.exe
hide_dlls = winmm.dll, reflex.dll
; Whenever Reflex should load and cleanup automatically the driver or not.
; This requires UAC elevation to work, as it needs to create a service and start it.
; If false, the user is expected to load the driver manually before starting the game.
; Defaults to false.
autoload = true
capcom = true

[load_dlls]
0 = coldclient/coldloader.dll

[patch:P4G.exe]
; Patches for Persona 4 Golden - add specific patches here if needed
; 4BFFF99 = EB
; 4C54E2F = E9C400000090

[hashes]
P4G.exe =